export const SECTION_NAME = 'SECTION_NAME';
/* export const REGISTER_ACTIVE = 'REGISTER_ACTIVE';
export const LOGIN_ACTIVE = 'LOGIN_ACTIVE';*/
export const DECISION_ACTIVE = 'DECISION_ACTIVE';
export const OCULTAR_NAV = 'OCULTAR_NAV'
export const ROUTE_AFTER = 'ROUTE_AFTER';
export const POST_DATA = 'POST_DATA';
export const ID_PADRE = 'ID_PADRE';
export const ID_ANCESTRO = 'ID_ANCESTRO';
export const SEARCH = 'SEARCH';
export const SEARCH_ACTIVE = 'SEARCH_ACTIVE';
export const USER_ACTIVE = 'USER_ACTIVE';
